apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    product: astrads
  name: astrads-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: operator
    product: astrads
status:
  loadBalancer: {}
