apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    product: astrads
  name: astrads-astradsvolumesnapshot-viewer-role
rules:
- apiGroups:
  - astrads.netapp.io
  resources:
  - astradsvolumesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - astrads.netapp.io
  resources:
  - astradsvolumesnapshots/status
  verbs:
  - get
