apiVersion: v1
data:
  events-asup.json: |
    {
        "events": [
            {
                "reason": "ADSClusterCreateSuccess",
                "namespace" : "astrads-system",
                "involvedObject": {
                    "apiVersion": "astrads.netapp.io/v1beta1",
                    "kind": "AstraDSCluster"
                }
            }
        ]
    }
kind: ConfigMap
metadata:
  labels:
    product: astrads
  name: astrads-kevents-asup
